In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [1176]:
import torch

## Basic tensor operation

In [1177]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.4798, 0.7684],
         [0.1496, 0.5070],
         [0.5990, 0.5332]],

        [[0.8974, 0.7629],
         [0.7021, 0.1340],
         [0.3128, 0.1686]],

        [[0.7776, 0.7571],
         [0.0980, 0.4335],
         [0.8818, 0.4470]],

        [[0.4783, 0.2949],
         [0.0878, 0.3683],
         [0.4201, 0.6364]]])

Display the size of the produced tensor

In [1178]:
tensor.size()

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [1179]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [1180]:
reshaped = tensor.reshape(4, 6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [1181]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
new_tensor = torch.tensor(list_to_transform)
new_tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [1182]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [1183]:
y = x + 3
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [1184]:
y = x * 3
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [1185]:
y = x ** 3
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [1186]:
k = torch.Tensor([8, 7, 5, 1])
y = x * k
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [1187]:
y = x ** k
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [1188]:
y = torch.exp(x)
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [1189]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b
y

tensor([0.0792, 0.1380, 0.0481, 0.0391, 0.4993])

Perform the dot product of `a` and `b`

In [1190]:
y = torch.sum(a * b)
y

tensor(0.8038)

Sum along the column axis of `l`

In [1191]:
l = torch.rand((5, 3, 6))
torch.sum(l,1)

tensor([[0.8062, 1.4574, 1.3177, 1.9231, 1.1686, 2.7203],
        [1.0574, 2.2408, 1.2127, 1.6622, 1.4697, 1.5021],
        [2.2607, 1.4077, 1.7566, 1.6427, 1.7320, 1.3631],
        [0.7226, 1.3277, 1.5219, 1.7622, 0.9273, 1.5393],
        [0.8828, 1.0317, 1.8256, 1.6636, 2.0644, 1.7044]])

## Slicing

Display the 3 last element of x

In [1192]:
x[(x.numel() - 3) : (x.numel())]

tensor([1, 2, 3])

Display the last element of x

In [1193]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [1194]:
m = torch.arange(18)
m[0::2].reshape(-1)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

Print only the first 2 rows of `matrix`

In [1195]:
matrix = torch.rand((6, 4, 2))
matrix[0:1, 0:2]

tensor([[[0.8084, 0.7857],
         [0.2797, 0.0334]]])

Now, only print the first 2 columns of `matrix`

In [1196]:
print(matrix)
matrix[0:2, : , 0:1]

tensor([[[0.8084, 0.7857],
         [0.2797, 0.0334],
         [0.8878, 0.5110],
         [0.3834, 0.6715]],

        [[0.4304, 0.5643],
         [0.2154, 0.9555],
         [0.2979, 0.0019],
         [0.0394, 0.2521]],

        [[0.5780, 0.8902],
         [0.3019, 0.1984],
         [0.9122, 0.7270],
         [0.9964, 0.3290]],

        [[0.0554, 0.3844],
         [0.1993, 0.3489],
         [0.5994, 0.8429],
         [0.4549, 0.7249]],

        [[0.7648, 0.7432],
         [0.0536, 0.1174],
         [0.7637, 0.0449],
         [0.5301, 0.2073]],

        [[0.5504, 0.8419],
         [0.3468, 0.7455],
         [0.0287, 0.3676],
         [0.6690, 0.7379]]])


tensor([[[0.8084],
         [0.2797],
         [0.8878],
         [0.3834]],

        [[0.4304],
         [0.2154],
         [0.2979],
         [0.0394]]])