In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [171]:
import torch

## Basic tensor operation

In [172]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.4636, 0.6080],
         [0.1170, 0.7305],
         [0.3101, 0.9600]],

        [[0.9216, 0.1652],
         [0.6792, 0.8369],
         [0.7051, 0.6153]],

        [[0.0307, 0.2651],
         [0.3545, 0.5048],
         [0.9696, 0.6124]],

        [[0.1154, 0.3498],
         [0.9168, 0.6483],
         [0.4144, 0.0091]]])

Display the size of the produced tensor

In [173]:
tensor.size()

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [174]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [175]:
reshaped = tensor.reshape(4, 6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [176]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
new_tensor = torch.tensor(list_to_transform)
new_tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [177]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [178]:
y = x + 3
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [179]:
y = x * 3
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [180]:
y = x ** 3
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [181]:
k = torch.Tensor([8, 7, 5, 1])
y = x * k
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [182]:
y = x ** k
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [183]:
y = torch.exp(x)
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [184]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b
y

tensor([0.0803, 0.5371, 0.1279, 0.0457, 0.2200])

Perform the dot product of `a` and `b`

In [185]:
y = torch.dot(a, b)
y

tensor(1.0111)

Sum along the column axis of `l`

In [186]:
l = torch.rand((5, 3, 6))
torch.sum(l,1)

tensor([[2.3791, 2.7258, 1.3116, 1.4012, 1.7093, 0.6515],
        [1.6047, 2.0460, 0.8214, 1.1897, 1.9308, 1.1476],
        [0.9239, 0.9447, 2.1370, 0.9331, 1.6278, 0.9751],
        [1.4029, 1.4425, 1.3162, 1.8231, 2.0918, 1.0193],
        [1.3572, 1.5283, 2.1533, 1.5194, 1.1145, 1.7744]])

## Slicing

Display the 3 last element of x

In [187]:
x[-3:]

tensor([1, 2, 3])

Display the last element of x

In [188]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [189]:
m = torch.arange(18)
m[::2] # = m[0::2]

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

Print only the first 2 rows of `matrix`

In [190]:
matrix = torch.rand((6, 4, 2)) # torch.arange(6*4*2).reshape(6,4,2) matrix[0:2]
matrix[:, 0:2]

tensor([[[0.1788, 0.9497],
         [0.9804, 0.4923]],

        [[0.2564, 0.7542],
         [0.6942, 0.0961]],

        [[0.2227, 0.2058],
         [0.1515, 0.1756]],

        [[0.8712, 0.7565],
         [0.4758, 0.7520]],

        [[0.3439, 0.9014],
         [0.1538, 0.8944]],

        [[0.3751, 0.3540],
         [0.7800, 0.9224]]])

Now, only print the first 2 columns of `matrix`

In [191]:
matrix[:, : , 0:2]

tensor([[[0.1788, 0.9497],
         [0.9804, 0.4923],
         [0.6031, 0.2066],
         [0.0524, 0.2617]],

        [[0.2564, 0.7542],
         [0.6942, 0.0961],
         [0.0770, 0.3477],
         [0.7969, 0.0970]],

        [[0.2227, 0.2058],
         [0.1515, 0.1756],
         [0.4539, 0.9455],
         [0.6068, 0.6273]],

        [[0.8712, 0.7565],
         [0.4758, 0.7520],
         [0.4082, 0.6842],
         [0.5468, 0.8659]],

        [[0.3439, 0.9014],
         [0.1538, 0.8944],
         [0.3908, 0.6576],
         [0.7083, 0.0079]],

        [[0.3751, 0.3540],
         [0.7800, 0.9224],
         [0.6521, 0.4418],
         [0.3749, 0.4379]]])