In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [1197]:
import torch

## Basic tensor operation

In [1198]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.3065, 0.3469],
         [0.4868, 0.6109],
         [0.2995, 0.5933]],

        [[0.2009, 0.0956],
         [0.7665, 0.5208],
         [0.3790, 0.8915]],

        [[0.2333, 0.4798],
         [0.6274, 0.0547],
         [0.4809, 0.2889]],

        [[0.1132, 0.1851],
         [0.5629, 0.2499],
         [0.9592, 0.7963]]])

Display the size of the produced tensor

In [1199]:
tensor.size()

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [1200]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [1201]:
reshaped = tensor.reshape(4, 6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [1202]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
new_tensor = torch.tensor(list_to_transform)
new_tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [1203]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [1204]:
y = x + 3
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [1205]:
y = x * 3
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [1206]:
y = x ** 3
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [1207]:
k = torch.Tensor([8, 7, 5, 1])
y = x * k
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [1208]:
y = x ** k
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [1209]:
y = torch.exp(x)
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [1210]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b
y

tensor([0.2108, 0.0466, 0.6634, 0.1585, 0.0163])

Perform the dot product of `a` and `b`

In [1211]:
y = torch.sum(a * b)
y

tensor(1.0955)

Sum along the column axis of `l`

In [1212]:
l = torch.rand((5, 3, 6))
torch.sum(l,1)

tensor([[1.4206, 0.4885, 1.0271, 2.0584, 1.7968, 1.8672],
        [1.6753, 1.5695, 1.0705, 1.9169, 1.5402, 0.8499],
        [1.2186, 2.0404, 1.7653, 2.8535, 1.4809, 1.7873],
        [0.9230, 1.4243, 2.2164, 2.0415, 0.8547, 1.4933],
        [1.3732, 1.1919, 1.1960, 1.2819, 1.8793, 1.6460]])

## Slicing

Display the 3 last element of x

In [1213]:
x[(x.numel() - 3) : (x.numel())]

tensor([1, 2, 3])

Display the last element of x

In [1214]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [1215]:
m = torch.arange(18)
m[0::2].reshape(-1)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

Print only the first 2 rows of `matrix`

In [1216]:
matrix = torch.rand((6, 4, 2))
matrix[0:1, 0:2]

tensor([[[0.2954, 0.4725],
         [0.0525, 0.0703]]])

Now, only print the first 2 columns of `matrix`

In [1217]:
matrix[0:2, : , 0:1]

tensor([[[0.2954],
         [0.0525],
         [0.3165],
         [0.1374]],

        [[0.8541],
         [0.3442],
         [0.6871],
         [0.1891]]])