In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [262]:
import torch

## Basic tensor operation

In [263]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.5897, 0.3767],
         [0.2694, 0.5787],
         [0.8774, 0.7268]],

        [[0.9318, 0.0789],
         [0.6916, 0.8273],
         [0.0615, 0.9861]],

        [[0.3521, 0.4847],
         [0.9804, 0.1387],
         [0.7751, 0.3880]],

        [[0.9781, 0.9521],
         [0.0050, 0.5644],
         [0.6435, 0.6749]]])

Display the size of the produced tensor

In [264]:
tensor.size()

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [265]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [266]:
reshaped = tensor.reshape(4, 6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [267]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
new_tensor = torch.tensor(list_to_transform)
new_tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [268]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [269]:
y = x + 3
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [270]:
y = x * 3
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [271]:
y = x ** 3
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [272]:
k = torch.Tensor([8, 7, 5, 1])
y = x * k
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [273]:
y = x ** k
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [274]:
y = torch.exp(x)
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [275]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b
y

tensor([0.0346, 0.0644, 0.2832, 0.2807, 0.2893])

Perform the dot product of `a` and `b`

In [276]:
y = torch.sum(a * b)
y

tensor(0.9522)

Sum along the column axis of `l`

In [277]:
l = torch.rand((5, 3, 6))
torch.sum(l,1)

tensor([[0.9653, 1.4985, 1.4353, 1.7501, 2.1071, 1.6287],
        [1.4553, 1.1574, 0.7955, 1.1816, 1.9635, 1.9921],
        [2.0513, 2.6570, 0.3118, 1.7051, 1.7386, 1.9467],
        [1.3988, 2.0531, 1.1971, 1.8958, 1.4634, 1.6208],
        [0.9370, 1.6869, 1.4684, 1.8088, 1.0430, 1.9219]])

## Slicing

Display the 3 last element of x

In [278]:
x[(x.numel() - 3) : (x.numel())]

tensor([1, 2, 3])

Display the last element of x

In [279]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [280]:
m = torch.arange(18)
#TODO

Print only the first 2 rows of `matrix`

In [281]:
matrix = torch.rand((6, 4, 2))
#TODO

Now, only print the first 2 columns of `matrix`

In [282]:
#TODO